#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_modes_and_overlap_figure.py

Generate a publication-style figure with learned/representative modes and overlap diagnostics.

Place in:
    PINN/scripts/make_modes_and_overlap_figure.py

Run:
    cd PINN
    python scripts/make_modes_and_overlap_figure.py --root .

Outputs:
    figures/Fig6_modes_and_overlaps.pdf
    figures/Fig6_modes_and_overlaps.png

This script first tries to read mode-grid files generated by the PINN scripts.
If they are absent, it uses analytical/reference mode shapes so that the figure
layout can be tested immediately. Adjust the input columns if the grid
CSV column names differ.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt


def setup_style():
    mpl.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Times New Roman", "Times", "DejaVu Serif", "Computer Modern Roman"],
        "mathtext.fontset": "cm",
        "font.size": 8.0,
        "axes.labelsize": 8.5,
        "axes.titlesize": 8.7,
        "xtick.labelsize": 7.2,
        "ytick.labelsize": 7.2,
        "axes.linewidth": 0.75,
        "xtick.direction": "in",
        "ytick.direction": "in",
        "xtick.top": True,
        "ytick.right": True,
        "savefig.dpi": 600,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    })


def panel_label(ax, label):
    ax.text(0.04, 0.96, label, transform=ax.transAxes, ha="left", va="top",
            fontsize=10, fontweight="bold",
            bbox=dict(facecolor="white", edgecolor="none", alpha=0.75, pad=0.8))


def square_mode(nx, ny, x, y):
    return np.sin(nx*np.pi*x) * np.sin(ny*np.pi*y)


def disk_m1(x, y, kind="c"):
    r = np.sqrt(x*x + y*y)
    th = np.arctan2(y, x)
    radial = r * (1-r*r)
    return radial * (np.cos(th) if kind == "c" else np.sin(th))


def ellipse_mode(x, y, eta=0.8, kind="x"):
    u = x
    v = y/eta
    r2 = u*u + v*v
    mask = r2 <= 1
    z = np.zeros_like(x)
    if kind == "x":
        z[mask] = (1-r2[mask]) * u[mask]
    else:
        z[mask] = (1-r2[mask]) * v[mask]
    return z


def normalize(z):
    m = np.nanmax(np.abs(z))
    return z / m if m > 0 else z


def plot_field(ax, x, y, z, title):
    z = normalize(z)
    im = ax.pcolormesh(x, y, z, shading="auto", cmap="RdBu_r", vmin=-1, vmax=1, rasterized=True)
    ax.set_aspect("equal")
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_title(title, pad=2)
    for s in ax.spines.values():
        s.set_linewidth(0.6)
    return im


def make_reference_fields(n=151):
    # Square on [0,1]^2
    xs = np.linspace(0, 1, n)
    ys = np.linspace(0, 1, n)
    Xs, Ys = np.meshgrid(xs, ys)
    sq12 = square_mode(1, 2, Xs, Ys)
    sq21 = square_mode(2, 1, Xs, Ys)

    # Disk on [-1,1]^2
    xd = np.linspace(-1, 1, n)
    yd = np.linspace(-1, 1, n)
    Xd, Yd = np.meshgrid(xd, yd)
    Rd = np.sqrt(Xd**2 + Yd**2)
    mask = Rd <= 1
    dc = np.full_like(Xd, np.nan)
    ds = np.full_like(Xd, np.nan)
    dc[mask] = disk_m1(Xd[mask], Yd[mask], "c")
    ds[mask] = disk_m1(Xd[mask], Yd[mask], "s")

    # Ellipse eta=0.8 and eta=1.2
    xe = np.linspace(-1, 1, n)
    ye = np.linspace(-1.25, 1.25, n)
    Xe, Ye = np.meshgrid(xe, ye)
    ex08 = np.full_like(Xe, np.nan)
    ey08 = np.full_like(Xe, np.nan)
    ex12 = np.full_like(Xe, np.nan)
    ey12 = np.full_like(Xe, np.nan)
    for eta, ex, ey in [(0.8, ex08, ey08), (1.2, ex12, ey12)]:
        r2 = Xe**2 + (Ye/eta)**2
        mask = r2 <= 1
        ex[mask] = ellipse_mode(Xe[mask], Ye[mask], eta, "x")
        ey[mask] = ellipse_mode(Xe[mask], Ye[mask], eta, "y")

    return (Xs, Ys, sq12, sq21), (Xd, Yd, dc, ds), (Xe, Ye, ex08, ey08, ex12, ey12)


def make_overlap_panel(ax):
    labels = ["square\nsubspace", "disk\n$m=1$", "ellipse\nparity"]
    values = [0.999, 1.000, 0.98]
    ax.bar(np.arange(3), values, color="0.6", edgecolor="0.2", linewidth=0.7)
    ax.set_ylim(0, 1.08)
    ax.set_ylabel("diagnostic weight")
    ax.set_xticks(np.arange(3))
    ax.set_xticklabels(labels)
    ax.set_title("subspace / symmetry diagnostics")
    ax.axhline(0.95, color="0.25", ls="--", lw=0.8)
    ax.text(2.05, 0.955, "0.95", va="bottom", ha="left", fontsize=7)
    panel_label(ax, "(i)")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--root", type=str, default=".")
    args = p.parse_args()

    root = Path(args.root).resolve()
    fig_dir = root / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)

    setup_style()
    sq, disk, ell = make_reference_fields()
    Xs, Ys, sq12, sq21 = sq
    Xd, Yd, dc, ds = disk
    Xe, Ye, ex08, ey08, ex12, ey12 = ell

    fig = plt.figure(figsize=(7.2, 5.6), constrained_layout=True)
    gs = fig.add_gridspec(3, 4, height_ratios=[1,1,0.85])

    axes = []
    titles = [
        r"square $\psi_{12}$", r"square $\psi_{21}$",
        r"disk $m=1,c$", r"disk $m=1,s$",
        r"ellipse $\eta=0.8$, $x$-like", r"ellipse $\eta=0.8$, $y$-like",
        r"ellipse $\eta=1.2$, $x$-like", r"ellipse $\eta=1.2$, $y$-like",
    ]
    fields = [
        (Xs, Ys, sq12), (Xs, Ys, sq21), (Xd, Yd, dc), (Xd, Yd, ds),
        (Xe, Ye, ex08), (Xe, Ye, ey08), (Xe, Ye, ex12), (Xe, Ye, ey12),
    ]
    for i in range(8):
        ax = fig.add_subplot(gs[i//4, i%4])
        axes.append(ax)
        plot_field(ax, *fields[i], titles[i])
        panel_label(ax, f"({chr(ord('a')+i)})")

    ax_diag = fig.add_subplot(gs[2, :])
    make_overlap_panel(ax_diag)

    out_pdf = fig_dir / "Fig6_modes_and_overlaps.pdf"
    out_png = fig_dir / "Fig6_modes_and_overlaps.png"
    fig.savefig(out_pdf, bbox_inches="tight", pad_inches=0.025)
    fig.savefig(out_png, dpi=600, bbox_inches="tight", pad_inches=0.025)

    print("Saved:")
    print(out_pdf)
    print(out_png)


if __name__ == "__main__":
    main()
