#!/usr/bin/env python3
"""Carrier-assisted avoided crossing generated by a real shear geometry.

The physical domain is the sheared rectangle

    x = u + gamma v,   y = eta v,      0<u<1, 0<v<1.

For gamma=0, the rectangular (1,2) and (2,1) branches cross at eta=1. A
nonzero shear introduces a geometric cross-derivative coupling through the
metric tensor and opens an avoided crossing without adding an artificial
potential.
"""

from __future__ import annotations

import argparse
import os
import random
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / ".cache"
CACHE.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLBACKEND", "Agg")
os.environ.setdefault("MPLCONFIGDIR", str(CACHE / "matplotlib"))
os.environ.setdefault("XDG_CACHE_HOME", str(CACHE))

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from scipy.linalg import eigh


OUT_DATA = ROOT / "data"
OUT_FIG = ROOT / "figures"


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)


def setup_style() -> None:
    mpl.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Times New Roman", "Times", "DejaVu Serif", "Computer Modern Roman"],
        "mathtext.fontset": "cm",
        "font.size": 7.5,
        "axes.labelsize": 8.0,
        "xtick.labelsize": 7.0,
        "ytick.labelsize": 7.0,
        "legend.fontsize": 6.3,
        "axes.linewidth": 0.7,
        "xtick.direction": "in",
        "ytick.direction": "in",
        "xtick.top": True,
        "ytick.right": True,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "savefig.dpi": 600,
    })


def gauss_square(n: int, device: torch.device, dtype: torch.dtype):
    g, w = np.polynomial.legendre.leggauss(n)
    u = 0.5 * (g + 1.0)
    wu = 0.5 * w
    U, V = np.meshgrid(u, u, indexing="ij")
    WU, WV = np.meshgrid(wu, wu, indexing="ij")
    pts = np.column_stack([U.ravel(), V.ravel()])
    weights = (WU * WV).ravel()
    return (
        torch.tensor(pts, device=device, dtype=dtype),
        torch.tensor(weights, device=device, dtype=dtype),
    )


def metric_terms(eta: float, gamma: float) -> tuple[float, float, float, float]:
    det = eta
    g11 = 1.0 + (gamma * gamma) / (eta * eta)
    g12 = -gamma / (eta * eta)
    g22 = 1.0 / (eta * eta)
    return det, g11, g12, g22


def sine_mode_np(u: np.ndarray, v: np.ndarray, nx: int, ny: int):
    psi = 2.0 * np.sin(nx * np.pi * u) * np.sin(ny * np.pi * v)
    du = 2.0 * nx * np.pi * np.cos(nx * np.pi * u) * np.sin(ny * np.pi * v)
    dv = 2.0 * ny * np.pi * np.sin(nx * np.pi * u) * np.cos(ny * np.pi * v)
    return psi, du, dv


def reference_spectrum(eta: float, gamma: float, nmax: int, nq: int) -> dict[str, object]:
    g, w = np.polynomial.legendre.leggauss(nq)
    x = 0.5 * (g + 1.0)
    wx = 0.5 * w
    U, V = np.meshgrid(x, x, indexing="ij")
    WU, WV = np.meshgrid(wx, wx, indexing="ij")
    uu = U.ravel()
    vv = V.ravel()
    ww = (WU * WV).ravel()
    modes = [(nx, ny) for nx in range(1, nmax + 1) for ny in range(1, nmax + 1)]
    nb = len(modes)
    phi = np.empty((uu.size, nb))
    du = np.empty_like(phi)
    dv = np.empty_like(phi)
    for j, (nx, ny) in enumerate(modes):
        phi[:, j], du[:, j], dv[:, j] = sine_mode_np(uu, vv, nx, ny)

    det, g11, g12, g22 = metric_terms(eta, gamma)
    M = det * (phi.T @ (ww[:, None] * phi))
    K = det * (
        g11 * (du.T @ (ww[:, None] * du))
        + g12 * (du.T @ (ww[:, None] * dv) + dv.T @ (ww[:, None] * du))
        + g22 * (dv.T @ (ww[:, None] * dv))
    )
    vals, vecs = eigh(K, M)
    order = np.argsort(vals)
    vals = vals[order]
    vecs = vecs[:, order]
    idx12 = modes.index((1, 2))
    idx21 = modes.index((2, 1))
    lower = vecs[:, 1]
    upper = vecs[:, 2]
    return {
        "vals": vals,
        "vecs": vecs,
        "modes": modes,
        "w12_lower": float(eta * lower[idx12] ** 2),
        "w21_lower": float(eta * lower[idx21] ** 2),
        "w12_upper": float(eta * upper[idx12] ** 2),
        "w21_upper": float(eta * upper[idx21] ** 2),
    }


def sine_torch(pts: torch.Tensor, nx: int, ny: int) -> torch.Tensor:
    u = pts[:, 0]
    v = pts[:, 1]
    return 2.0 * torch.sin(nx * torch.pi * u) * torch.sin(ny * torch.pi * v)


class CorrectionNet(nn.Module):
    def __init__(self, width: int, layers: int, fourier: int) -> None:
        super().__init__()
        self.fourier = int(fourier)
        in_dim = 2 + 4 * self.fourier
        seq: list[nn.Module] = []
        last = in_dim
        for _ in range(layers):
            layer = nn.Linear(last, width)
            nn.init.xavier_uniform_(layer.weight)
            nn.init.zeros_(layer.bias)
            seq.append(layer)
            seq.append(nn.Tanh())
            last = width
        out = nn.Linear(last, 2)
        nn.init.xavier_uniform_(out.weight)
        nn.init.zeros_(out.bias)
        seq.append(out)
        self.net = nn.Sequential(*seq)

    def features(self, pts: torch.Tensor) -> torch.Tensor:
        u = pts[:, 0:1]
        v = pts[:, 1:2]
        feats = [u, v]
        for k in range(1, self.fourier + 1):
            kk = float(k)
            feats.extend([
                torch.sin(2.0 * torch.pi * kk * u),
                torch.cos(2.0 * torch.pi * kk * u),
                torch.sin(2.0 * torch.pi * kk * v),
                torch.cos(2.0 * torch.pi * kk * v),
            ])
        return torch.cat(feats, dim=1)

    def forward(self, pts: torch.Tensor) -> torch.Tensor:
        return self.net(self.features(pts))


def first_derivatives(y: torch.Tensor, pts: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    grad = torch.autograd.grad(
        y,
        pts,
        grad_outputs=torch.ones_like(y),
        create_graph=True,
        retain_graph=True,
    )[0]
    return grad[:, 0], grad[:, 1]


def carrier_fields(model: CorrectionNet, pts_base: torch.Tensor, alpha: float):
    pts = pts_base.detach().clone().requires_grad_(True)
    u = pts[:, 0]
    v = pts[:, 1]
    boundary = u * (1.0 - u) * v * (1.0 - v)
    corr = model(pts)
    phi1 = sine_torch(pts, 1, 2) + alpha * boundary * corr[:, 0]
    phi2 = sine_torch(pts, 2, 1) + alpha * boundary * corr[:, 1]
    Phi = torch.stack([phi1, phi2], dim=1)
    Du = []
    Dv = []
    for k in range(2):
        du, dv = first_derivatives(Phi[:, k], pts)
        Du.append(du)
        Dv.append(dv)
    return pts, Phi, torch.stack(Du, dim=1), torch.stack(Dv, dim=1), corr, boundary


def ritz(model: CorrectionNet, pts: torch.Tensor, w: torch.Tensor, eta: float, gamma: float, alpha: float, jitter: float):
    _, Phi, Du, Dv, _, _ = carrier_fields(model, pts, alpha)
    det, g11, g12, g22 = metric_terms(eta, gamma)
    W = det * w[:, None]
    M = Phi.T @ (W * Phi)
    K = det * (
        g11 * (Du.T @ (w[:, None] * Du))
        + g12 * (Du.T @ (w[:, None] * Dv) + Dv.T @ (w[:, None] * Du))
        + g22 * (Dv.T @ (w[:, None] * Dv))
    )
    M = 0.5 * (M + M.T) + jitter * torch.eye(2, dtype=M.dtype, device=M.device)
    K = 0.5 * (K + K.T)
    L = torch.linalg.cholesky(M)
    A = torch.cholesky_solve(K, L)
    A = 0.5 * (A + A.T)
    vals, vecs_std = torch.linalg.eigh(A)
    vecs = torch.linalg.solve_triangular(L.T, vecs_std, upper=True)
    return vals, vecs, K, M


def correction_penalty(model: CorrectionNet, pts_base: torch.Tensor, w: torch.Tensor, eta: float, gamma: float, alpha: float):
    pts, _, _, _, corr, boundary = carrier_fields(model, pts_base, alpha)
    delta = alpha * boundary[:, None] * corr
    det, g11, g12, g22 = metric_terms(eta, gamma)
    amp = torch.sum(w[:, None] * corr.pow(2)) / 2.0
    h1 = torch.zeros((), dtype=pts.dtype, device=pts.device)
    for k in range(2):
        du, dv = first_derivatives(delta[:, k], pts)
        grad = g11 * du.pow(2) + 2.0 * g12 * du * dv + g22 * dv.pow(2)
        h1 = h1 + torch.sum(w * (delta[:, k].pow(2) + grad))
    return amp, 0.5 * det * h1


def train_eta(eta: float, args: argparse.Namespace, device: torch.device, dtype: torch.dtype):
    pts, w = gauss_square(args.nq, device, dtype)
    pts_val, w_val = gauss_square(args.nq_val, device, dtype)
    best = None
    best_score = float("inf")
    t0 = time.time()
    for restart in range(args.restarts):
        set_seed(args.seed + 1000 * restart + int(round(1000 * eta)))
        model = CorrectionNet(args.width, args.layers, args.fourier).to(device=device, dtype=dtype)
        opt = torch.optim.Adam(model.parameters(), lr=args.lr)
        for epoch in range(1, args.epochs + 1):
            opt.zero_grad(set_to_none=True)
            vals, _, _, _ = ritz(model, pts, w, eta, args.gamma, args.alpha, args.jitter)
            amp, h1 = correction_penalty(model, pts, w, eta, args.gamma, args.alpha)
            loss = torch.sum(vals) + args.lambda_corr * amp + args.lambda_h1corr * h1
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
            opt.step()
        with torch.enable_grad():
            vals, _, _, M = ritz(model, pts_val, w_val, eta, args.gamma, args.alpha, args.jitter)
        score = float(torch.sum(vals).detach().cpu())
        if score < best_score:
            best_score = score
            best = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
    model = CorrectionNet(args.width, args.layers, args.fourier).to(device=device, dtype=dtype)
    model.load_state_dict(best)
    vals, vecs, _, M = ritz(model, pts_val, w_val, eta, args.gamma, args.alpha, args.jitter)
    pts_req, Phi, _, _, _, _ = carrier_fields(model, pts_val, args.alpha)
    mode_lower = Phi @ vecs[:, 0]
    mode_upper = Phi @ vecs[:, 1]
    psi12 = sine_torch(pts_req, 1, 2)
    psi21 = sine_torch(pts_req, 2, 1)
    det = eta
    norm12 = torch.sqrt(det * torch.sum(w_val * psi12.pow(2)))
    norm21 = torch.sqrt(det * torch.sum(w_val * psi21.pow(2)))

    def weights(mode: torch.Tensor):
        c12 = det * torch.sum(w_val * mode * psi12) / norm12
        c21 = det * torch.sum(w_val * mode * psi21) / norm21
        return float((c12 * c12).detach().cpu()), float((c21 * c21).detach().cpu())

    w12_l, w21_l = weights(mode_lower)
    w12_u, w21_u = weights(mode_upper)
    mcond = float(torch.linalg.cond(M).detach().cpu())
    return vals.detach().cpu().numpy(), (w12_l, w21_l, w12_u, w21_u), mcond, time.time() - t0


def uncoupled_energy(eta: float, nx: int, ny: int) -> float:
    return float(np.pi**2 * (nx * nx + (ny * ny) / (eta * eta)))


def make_figure(summary: pd.DataFrame) -> None:
    setup_style()
    eta = summary["eta"]
    fig = plt.figure(figsize=(7.05, 2.35))
    gs = fig.add_gridspec(1, 3, width_ratios=[1.25, 1.05, 0.82], wspace=0.34)
    ax = fig.add_subplot(gs[0, 0])
    ax.plot(eta, summary["E12_uncoupled"], "--", color="0.68", lw=0.9, label=r"unsheared $(1,2)$")
    ax.plot(eta, summary["E21_uncoupled"], ":", color="0.58", lw=1.2, label=r"unsheared $(2,1)$")
    ax.plot(eta, summary["E2_ref"], "-", color="0.08", lw=1.15, label="spectral ref.")
    ax.plot(eta, summary["E3_ref"], "-", color="0.08", lw=1.15)
    ax.plot(eta, summary["E2_pinn"], "o", mfc="white", mec="0.08", mew=0.75, ms=3.0, label="carrier RR-PINN")
    ax.plot(eta, summary["E3_pinn"], "s", mfc="white", mec="0.08", mew=0.75, ms=3.0)
    ax.set_xlabel(r"$\eta$")
    ax.set_ylabel(r"$\epsilon$")
    ax.legend(loc="upper right", handlelength=2.0)
    ax.text(-0.12, 1.04, "(a)", transform=ax.transAxes, fontweight="bold")

    ax = fig.add_subplot(gs[0, 1])
    ax.plot(eta, summary["w12_lower_ref"], "-", color="0.08", lw=1.15, label=r"ref. $w_{12}$")
    ax.plot(eta, summary["w21_lower_ref"], "--", color="0.08", lw=1.15, label=r"ref. $w_{21}$")
    ax.plot(eta, summary["w12_lower_pinn"], "o", mfc="white", mec="0.08", mew=0.75, ms=3.0, label=r"PINN $w_{12}$")
    ax.plot(eta, summary["w21_lower_pinn"], "s", mfc="white", mec="0.08", mew=0.75, ms=3.0, label=r"PINN $w_{21}$")
    ax.set_xlabel(r"$\eta$")
    ax.set_ylabel("lower-branch weight")
    ax.set_ylim(-0.28, 1.04)
    ax.set_yticks([0, 0.5, 1])
    ax.legend(loc="lower center", bbox_to_anchor=(0.54, 0.02), ncol=2, fontsize=5.8, handlelength=1.8)
    ax.text(-0.12, 1.04, "(b)", transform=ax.transAxes, fontweight="bold")

    ax = fig.add_subplot(gs[0, 2])
    ax.plot(eta, summary["gap_ref"], "-", color="0.08", lw=1.15, label="spectral ref.")
    ax.plot(eta, summary["gap_pinn"], "o", mfc="white", mec="0.08", mew=0.75, ms=3.0, label="carrier")
    ax.set_xlabel(r"$\eta$")
    ax.set_ylabel(r"$E_3-E_2$")
    ax.legend(loc="upper right")
    ax.text(-0.12, 1.04, "(c)", transform=ax.transAxes, fontweight="bold")
    out = OUT_FIG / "Fig_avoided_crossing_geom"
    fig.savefig(out.with_suffix(".pdf"), bbox_inches="tight", pad_inches=0.018)
    fig.savefig(out.with_suffix(".png"), dpi=300, bbox_inches="tight", pad_inches=0.018)
    plt.close(fig)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--eta-min", type=float, default=0.82)
    p.add_argument("--eta-max", type=float, default=1.18)
    p.add_argument("--n-eta", type=int, default=13)
    p.add_argument("--gamma", type=float, default=0.18)
    p.add_argument("--alpha", type=float, default=0.05)
    p.add_argument("--lambda-corr", type=float, default=1e-2)
    p.add_argument("--lambda-h1corr", type=float, default=100.0)
    p.add_argument("--nmax-ref", type=int, default=10)
    p.add_argument("--nq-ref", type=int, default=72)
    p.add_argument("--nq", type=int, default=48)
    p.add_argument("--nq-val", type=int, default=64)
    p.add_argument("--epochs", type=int, default=800)
    p.add_argument("--restarts", type=int, default=2)
    p.add_argument("--width", type=int, default=48)
    p.add_argument("--layers", type=int, default=2)
    p.add_argument("--fourier", type=int, default=4)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--jitter", type=float, default=1e-10)
    p.add_argument("--grad-clip", type=float, default=10.0)
    p.add_argument("--seed", type=int, default=2026)
    p.add_argument("--device", default="cpu")
    p.add_argument("--dtype", choices=["float32", "float64"], default="float64")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    OUT_DATA.mkdir(parents=True, exist_ok=True)
    OUT_FIG.mkdir(parents=True, exist_ok=True)
    device = torch.device(args.device)
    dtype = torch.float64 if args.dtype == "float64" else torch.float32
    rows = []
    for i, eta in enumerate(np.linspace(args.eta_min, args.eta_max, args.n_eta), start=1):
        ref = reference_spectrum(float(eta), args.gamma, args.nmax_ref, args.nq_ref)
        vals_pinn, weights, mcond, runtime = train_eta(float(eta), args, device, dtype)
        e2_ref = float(ref["vals"][1])
        e3_ref = float(ref["vals"][2])
        e2_pinn = float(vals_pinn[0])
        e3_pinn = float(vals_pinn[1])
        row = {
            "eta": float(eta),
            "gamma_shear": args.gamma,
            "E12_uncoupled": uncoupled_energy(float(eta), 1, 2),
            "E21_uncoupled": uncoupled_energy(float(eta), 2, 1),
            "E2_ref": e2_ref,
            "E3_ref": e3_ref,
            "gap_ref": e3_ref - e2_ref,
            "E2_pinn": e2_pinn,
            "E3_pinn": e3_pinn,
            "gap_pinn": e3_pinn - e2_pinn,
            "err_E2_percent": 100.0 * abs(e2_pinn - e2_ref) / abs(e2_ref),
            "err_E3_percent": 100.0 * abs(e3_pinn - e3_ref) / abs(e3_ref),
            "M_cond": mcond,
            "w12_lower_ref": ref["w12_lower"],
            "w21_lower_ref": ref["w21_lower"],
            "w12_upper_ref": ref["w12_upper"],
            "w21_upper_ref": ref["w21_upper"],
            "w12_lower_pinn": weights[0],
            "w21_lower_pinn": weights[1],
            "w12_upper_pinn": weights[2],
            "w21_upper_pinn": weights[3],
            "runtime_s": runtime,
        }
        rows.append(row)
        pd.DataFrame(rows).to_csv(OUT_DATA / "avoided_crossing_geom_summary.csv", index=False)
        print(
            f"{i:02d}/{args.n_eta} eta={eta:.3f}: ref=({e2_ref:.6f},{e3_ref:.6f}), "
            f"pinn=({e2_pinn:.6f},{e3_pinn:.6f}), "
            f"err=({row['err_E2_percent']:.3f}%,{row['err_E3_percent']:.3f}%), "
            f"Mcond={mcond:.3g}"
        )
    df = pd.DataFrame(rows)
    df.to_csv(OUT_DATA / "avoided_crossing_geom_summary.csv", index=False)
    make_figure(df)
    print("\nSaved:")
    print(OUT_DATA / "avoided_crossing_geom_summary.csv")
    print(OUT_FIG / "Fig_avoided_crossing_geom.pdf")
    print(OUT_FIG / "Fig_avoided_crossing_geom.png")


if __name__ == "__main__":
    main()
